let obj= '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>patches</key>
	<array>
		<dict>
			<key>UUID</key>
			<string>8EC2F72E-3B28-4997-A3CA-6DC55AA4A96A</string>
			<key>apiVersion</key>
			<integer>3</integer>
			<key>appIdentifier</key>
			<string>com.lightricks.Enlight-Quickart</string>
			<key>appVersion</key>
			<string>1.0.6</string>
			<key>cloudDescription</key>
			<string></string>
			<key>name</key>
			<string>☭ Quickart 会员PJ</string>
			<key>switchedOn</key>
			<true/>
			<key>units</key>
			<array>
				<dict>
					<key>methodObjc</key>
					<dict>
						<key>className</key>
						<string>ENSubscriberInfo</string>
						<key>displayName</key>
						<string>- (bool)​isSubscribed</string>
						<key>prefix</key>
						<string>-</string>
						<key>selector</key>
						<string>isSubscribed</string>
						<key>typeEncoding</key>
						<string>B16@0:8</string>
					</dict>
					<key>name</key>
					<string></string>
					<key>overrides</key>
					<array>
						<dict>
							<key>argument</key>
							<integer>0</integer>
							<key>type</key>
							<dict>
								<key>subtype</key>
								<integer>0</integer>
								<key>type</key>
								<integer>6</integer>
							</dict>
							<key>value</key>
							<dict>
								<key>type</key>
								<integer>6</integer>
								<key>value</key>
								<true/>
							</dict>
						</dict>
					</array>
				</dict>
				<dict>
					<key>methodObjc</key>
					<dict>
						<key>className</key>
						<string>EUISMYourPlanView</string>
						<key>displayName</key>
						<string>- (void)​setTitle:(id)</string>
						<key>prefix</key>
						<string>-</string>
						<key>selector</key>
						<string>setTitle:</string>
						<key>typeEncoding</key>
						<string>v24@0:8@16</string>
					</dict>
					<key>name</key>
					<string>名字</string>
					<key>overrides</key>
					<array>
						<dict>
							<key>argument</key>
							<integer>1</integer>
							<key>type</key>
							<dict>
								<key>subtype</key>
								<integer>1</integer>
								<key>type</key>
								<integer>1</integer>
							</dict>
							<key>value</key>
							<dict>
								<key>type</key>
								<integer>1</integer>
								<key>value</key>
								<string>General_xue QQ52455301</string>
							</dict>
						</dict>
					</array>
				</dict>
				<dict>
					<key>methodObjc</key>
					<dict>
						<key>className</key>
						<string>EUISMYourPlanView</string>
						<key>displayName</key>
						<string>- (void)​setSubtitle:(id)</string>
						<key>prefix</key>
						<string>-</string>
						<key>selector</key>
						<string>setSubtitle:</string>
						<key>typeEncoding</key>
						<string>v24@0:8@16</string>
					</dict>
					<key>name</key>
					<string>类型</string>
					<key>overrides</key>
					<array>
						<dict>
							<key>argument</key>
							<integer>1</integer>
							<key>type</key>
							<dict>
								<key>subtype</key>
								<integer>1</integer>
								<key>type</key>
								<integer>1</integer>
							</dict>
							<key>value</key>
							<dict>
								<key>type</key>
								<integer>1</integer>
								<key>value</key>
								<string>终身会员</string>
							</dict>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
</dict>
</plist>
';
$done({body: obj});
